name: GitHub Actions Demo
# https://stackoverflow.com/questions/71679906/how-to-github-action-parallelize-tests-dynamically-by-folder

run-name: Validate configs 🚀
on: [push]
jobs:
  validate:
    name: Validate Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for server in tests/*/ ; 
          do
            echo "### Checking json files for $server" >> $GITHUB_STEP_SUMMARY
            for jsonfile in $server*.json ; 
            do
                echo "- $jsonfile" >> $GITHUB_STEP_SUMMARY
                cat $jsonfile | jq
            done;
          done;