name: GitHub Actions Demo
# https://stackoverflow.com/questions/71679906/how-to-github-action-parallelize-tests-dynamically-by-folder

run-name: Validate configs 🚀
on: [push]
jobs:
  validate:
    name: Validate Server
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install jsonlint
        run: |
          sudo npm install jsonlint -g
      - id: lookup
        run: |
          ls -d tests/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]' > folders.json
          echo "servers=$(cat folders.json)" >> $GITHUB_OUTPUT
          for server in tests/*/ ; 
          do
            echo "### Checking json files for $server" >> $GITHUB_STEP_SUMMARY
            for jsonfile in $server*.json ; 
            do
                echo "- $jsonfile" >> $GITHUB_STEP_SUMMARY
                jsonlint $jsonfile -c >> $GITHUB_STEP_SUMMARY
            done;
          done;